### ISSUE TITLE
site stuck on "started rendering the images"

### ISSUE THREAD

**Issue by hyprfixation** [FoxGaal/SkyboxFixer#1]
![Screenshot 2024-11-29 164631](https://github.com/user-attachments/assets/368d3d90-1571-4a32-95b1-a68245176c6c)

**Comment by FoxGaal** [comment]
this is an issue with environment variables not being setup correctly, either run the setup again or add blender path manually, make sure you haven't downloaded Microsoft store blender

**Comment by FoxGaal** [comment]
![image](https://github.com/user-attachments/assets/6bac7bee-26c1-4dda-b8aa-9d8bb6a831c2)
Check `C:\Program Files\Blender Foundation\` for the correct blender folder if there are no blender folders uninstall blender and download from blender.org

**Comment by FoxGaal** [comment]
if you need any more help contact me on discord "foxgaal"
